[env]
platform = espressif32
framework = arduino

monitor_speed = 115200

[esp32dev_base]
board = esp32dev
monitor_filters = esp32_exception_decoder
build_unflags = -std=gnu++11
build_flags =
    ${env.build_flags}
    -Wswitch-enum
    -std=gnu++17
    -mfix-esp32-psram-cache-issue
    -DBOARD_HAS_PSRAM
extra_scripts = platformio_override.py
board_build.filesystem = littlefs
lib_deps =
    https://github.com/lewisxhe/TinyGSM-fork
    arduino-libraries/ArduinoHttpClient@^0.6.1
    adafruit/Adafruit NeoPixel@^1.12.3
    adafruit/Adafruit PN532@^1.3.4
    bblanchon/ArduinoJson@^7.2.0

[env:dev]
extends = esp32dev_base
build_type = debug

[env:prod]
extends = esp32dev_base
build_type = release
