#pragma once

#define SERVER_VERSION_ROUTE "/v1"

// Server router paths
#define LOG_ROUTE SERVER_VERSION_ROUTE "/log"
#define GPS_ROUTE SERVER_VERSION_ROUTE "/gps"
#define FIRMWARE_ROUTE SERVER_VERSION_ROUTE "/firmware"
#define RFIDS_ROUTE SERVER_VERSION_ROUTE "/rfids"
#define STATIC_ROUTE SERVER_VERSION_ROUTE "/static"

// Log route
#define LOG_FILE_UPLOAD_ENDPOINT LOG_ROUTE "/upload"

// Gps route
#define GPS_FILE_UPLOAD_ENDPOINT GPS_ROUTE "/upload"

// Firmware route
#define LATEST_FIRMWARE_ENDPOINT FIRMWARE_ROUTE "/latest"
#define LATEST_FIRMWARE_DOWNLOAD_PATH LATEST_FIRMWARE_ENDPOINT
#define LATEST_FIRMWARE_IS_NEWER_ENDPOINT FIRMWARE_ROUTE "/is-newer-available"
#define LATEST_FIRMWARE_SIZE_ENDPOINT LATEST_FIRMWARE_ENDPOINT "/latest"

// RFIDs route
#define REMOTE_RFID_MD5_CHECKSUM_PATH RFIDS_ROUTE "/md5-checksum"
#define REMOTE_RFID_PATH RFIDS_ROUTE "/download"
#define REMOTE_GPS_TRACKING_CONSENTED_RFIDS_PATH RFIDS_ROUTE "/gps-tracking-consented/download"

// Static route
#define REMOTE_STATIC_SPEED_TEST_DIR STATIC_ROUTE "/test-files"
#define REMOTE_STATIC_SPEED_TEST_8KIB_FILE REMOTE_STATIC_SPEED_TEST_DIR "/8KiB.bin"
#define REMOTE_STATIC_SPEED_TEST_16KIB_FILE REMOTE_STATIC_SPEED_TEST_DIR "/16KiB.bin"
#define REMOTE_STATIC_SPEED_TEST_32KIB_FILE REMOTE_STATIC_SPEED_TEST_DIR "/32KiB.bin"
#define REMOTE_STATIC_SPEED_TEST_64KIB_FILE REMOTE_STATIC_SPEED_TEST_DIR "/64KiB.bin"
